name = "bajamar-buzon"
main = "src/index.js"
compatibility_date = "2025-06-01"
workers_dev = true

# El namespace se crea una sola vez y el id se pega aquí:
#   wrangler kv namespace create BUZONES
[[kv_namespaces]]
binding = "BUZONES"
id = "7f325c35cc1248ad83037172a62c749e"
